### ISSUE TITLE
Error while compiling 

### ISSUE THREAD

**Issue by dukenst2006** [djaiss/officelife#222]
Hi @djaiss great project, thanks for your awesome work. trying to give it a try but i got some issues, any idea or i can fix that errors?

ERROR in ./resources/js/app.js
Module not found: Error: Can't resolve '../../public/js/langs/en.json' in '/Users/dukens/Code/officelife/resources/js'

GET https://officelife.test/nprogress/nprogress.css net::ERR_ABORTED 404 (Not Found)

Thanks 🙏

**Comment by djaiss** [comment]
You have to run `php artisan lang:generate`.
However this project is far, far from being ready to production or even testing. I strongly suggest that you wait a few months to try it out again, as I break many things until it’s ready.
